---
title: "Linear Model Walkthrough"
author: "Bruno Contrino and Piero Ricchiuto"
output: 
  html_document:
    theme: cosmo
    toc: true
    toc_float: true
---



##Linear Model Walkthrough

This walkthrough will explain step by step how to apply a linear model to your data using DOSCHEDA. There is a separate walkthrough dedicated to the sigmoidal model choice.    
The linear model must have at least 2 replicates and 3 different concentrations and can take peptide intensities or protein (log)fold changes as input.     
When uploading peptide intensities, DOSCHEDA offers the option to carry out a peptide removal process (please refer to the manual for a detailed description), this is designed to reduce the noise in your experiment between replicates by removing 'noisy' peptides from the data. See Table 1 for guidance on which model to fit.


|                     |1 Replicate |More than 1 Replicate |
|:--------------------|:-----------|:---------------------|
|**Less than 5 channels** |Not enough data      |Linear                |
|**5 or more channels**   |Sigmoidal   |Linear                |

Table: Table 1: Possible model fit depending on data input.  

### Data

|                    |Input                                                                                   |
|:-------------------|:---------------------------------------------------------------------------------------|
|**Peptide Intensities** |Peptide Qvality Score, Protein Accessions, Peptide Names, Intensities  |
|**Fold Changes**        |Protein Fold Changes         |
|**Log-Fold Changes**    |Protein log-Fold Changes    |

Table: Table 2: Required columns for the input data.

Your data will need to contain the columns as described in Table 2.

### Uploading the Data

The following will give a step by step guide on how to upload data.   
In *italics* will be the actions to execute in DOSCHEDA for processing the specific example input files that can be downloaded from GitHub repository https://github.com/brunocontrino/DOSCHEDA/tree/master/data.


####Uploading intensities
    
*(using the file: LinearIntensities.csv)*

1. Select **Intensities** in the '**Data  Type:**' section.

2. Select your file type from the options in the '**File Type:**'  
  *Select the 'csv' option*
  + To use the Peptide removal process, select **Yes** in the **Do removal** radio buttons.

3. Go to the '**Choose File**' section and click **Browse...** and select the file to be analysed.  
      *Select the LinearIntensities.csv file from your computer*

4. Select the correct number of channels and replicates in the **\#Channels** and **\#Replicates** sections respectively.    
  *In the '\# Channels' box put 6. In the '\# Replicates' box put 2.*

5. Input the columns with the correct intensities in the box which appears with a random selection of your data column names.  
  *The columns to import are: Abundance..F1..126..Control..REP_1,	Abundance..F1..126..Control..REP_2,	Abundance..F1..126..Control..REP_3,	Abundance..F1..126..Control..REP_4,	Abundance..F1..126..Control..REP_5,	Abundance..F1..126..Control..REP_6,	Abundance..F1..126..Control..REP_7,	Abundance..F1..126..Control..REP_8,	Abundance..F1..126..Control..REP_9,	Abundance..F1..126..Control..REP_10,	Abundance..F1..126..Control..REP_11,	Abundance..F1..126..Control..REP_12*
  
6. Go to the **Choose Sequence** drop down list and select the column name for the column containing the peptide sequences in your data.    
  *Select Sequence*

7. Go to the **Select Peptide Qvality Score:** drop down list and select the column containing peptide qvality score.  
  *Select 'Qvality.PEP'*
  
8. Go to the **Choose Accession** drop down list and select the column contaitng protein accessions.  
  *Select Master.Protein.Accessions*

11. Select one of the plot tabs and wait for the loading sign in the top left to finish.  


####Uploading protein fold changes 
*(using the file: LinearFC.csv)* 

1. Select **FC** or **Log FC**  
 *Select 'Log FC'*

2. Select **File Type**   
  *Select 'csv'*

3. Click **Browse** and select the file.  
*Select the 'LinearFC.csv' from your computer*

4. Select the correct number of channels and replicates in the **\#Channels** and **\#Replicates** section respectively.  
  *In the '\# Channels' box put 3. In the '\# Replicates' box put 2.*


5. Input the columns with the correct log fold changes.
  *The columns to import are: A6..114.115_norm_log2,	A6..114.116_norm_log2,	A6..114.117_norm_log2,	B6..114.115_norm_log2,	B6..114.116_norm_log2,	B6..114.117_norm_log2*  
  
+ For data obtained not from PD 2.1, tick the box **Data NOT PD 2.1** insert the column corresponding to the number of Unique Peptides and the Uniprot protein accession numbers from their respective drop down lists.


11. Select one of the plot tabs and wait for the loading sign in the top left to return to the DOSCHEDA logo. 

### Gene ID and CRAPome
In the downloaded results DOSCHEDA reports an extra column which contains the number of times (in \%) that a given protein was found as contaminant in a set of experiments. These experiments are organized in what is named *The CRAPome database*, downloaded from http://141.214.172.226/?q=Download and embedded in DOSCHEDA.   
To generate this extra column in the downloaded results, the user should change the organism which will be used to determine the accession number to Gene ID conversion by changing the organism in the **Select your organism:** section in the **Data Upload** tab. 
Currently, the available organisms are Human, Mouse and Yeast, if your organism is not among these, DOSCHEDA will simply return the Human percentages for the matched gene symbols.   
Note that this part of the pipeline will not impact the outcome of the statistical analysis or quality controls, if the organism of interest is not available.    



### Plots

Several plots are available for the visualisation of the results including typical quality control box plots and ranked density distributions.

|Plot                          |Description                                                                                                                                                          |Type     |
|:-----------------------------|:--------------------------------------------------------------------------------------------------------------------------------------------------------------------|:--------|
|Box                           |A box plot showing the mean and the interquartile range of each channel                                                                                              |QC       |
|Density and ranked protein    |These plots show the density distribution of each channel and the distribution of the ranked proteins                                                                |QC       |
|Venn                          |The intersection of the kinome and the inputted proteins. There is also the option to load a list of protein names and see the intersection with a personalised list |QC       |
|MeanSD                        |Shows the ranked means with a running median calculated with a window of 10%                                                                                         |QC       |
|Mean vs Difference            |Shows the mean protein fold change and difference between replicates                                                                                    |QC       |
|Corrgram                      |Pearson Correlation Coefficient between each channel                                                                                                                 |QC       |
|Compare Replicates            |The fold change per protein plotted againt each other in each replicate                                                                                              |Analysis |
|PCA                           |Each channel is plotted in the first two principal components of the data                                                                                            |Analysis |
|Heatmap                       |Interactive heatmap of the values per protein per channel                                                                                                            |Analysis |
|Linear Model: P-values        |The distribution of p-values for each coefficient of the linear model, that is the intecept, slope and quadratic                                                     |Analysis |
|Linear Model: volcano plots   |The distribution of proteins by their mean and standard deviation coloured by their p-values, there is a plot for each coeffcient in the linear model                |Analysis |

Table: Table 3: DOSCHEDA plots for the linear model.


### Downloading Results 
From the **Download** tab users can save their processed data by clicking on the **Download Data** button. Also in the same tab, the **Download Report** button enables users to download an HTML report containing all the plots seen in the analysis with descriptions as well as other important information such as the options selected during the workflow including the number of channels, replicates and the statistical fit applied for the data analysis.


### More Informaion and Help 

If you would like to know more about the pipeline used in the DOSCHEDA analysis, please refer to the user manual, this can be accessed at the following https://github.com/brunocontrino/DOSCHEDA.

