---
title: "Sigmoidal Walkthrough"
author: "Bruno Contrino and Piero Ricchiuto"
output: 
  html_document:
    theme: cosmo
    toc: true
    toc_float: true
---


##Sigmoidal Model Walkthrough

This walkthrough will explain step by step how to apply a sigmoidal fit using DOSCHEDA. There are some important pre-requisites in order to fit this type of model. These are: **At least 5 channels** and **one replicate**. The user will also need to know the concentrations of the drug that each of the channels corresponds to. See Table 1 for guidance on which model to fit.     


|                     |1 Replicate |More than 1 Replicate |
|:--------------------|:-----------|:---------------------|
|**Less than 5 channels** |Not enough data      |Linear                |
|**5 or more channels**   |Sigmoidal   |Linear                |

Table: Table 1: Possibile analysis given the experimental design.

### Data

|                    |Input                                                                                   |
|:-------------------|:---------------------------------------------------------------------------------------|
|**Peptide Intensities** |Peptide Qvality Score, Protein Accessions, Peptide Names, Intensities |
|**Fold Changes**        |Protein Fold Changes        |
|**Log-Fold Changes**    |Protein log-Fold Changes     |

Table: Table 2: Required columns containg the following data given data type.     

In order to use DOSCHEDA with a sigmoidal fit, as well as the pre-requisites mentioned in the introduction, the data will need contain the columns as described in Table 2.

### Uploading the Data

The following will give a step by step guide on how to upload data.   

In *italics* will be the actions to execute in DOSCHEDA for processing the specific example input files that can be downloaded from the GitHub repository https://github.com/brunocontrino/DOSCHEDA/tree/master/data.

####Uploading intensities
*(using the file: SigmoidalIntensities.csv)*

1. Select **intensities**   

2. Select **File Type**  
        *Select 'csv' option for radio button*

3. Click **Browse** and select the file.  
   *Select the SigmoidalIntensities.csv file from your computer*

4. Select the correct number of channels and replicates in the corresponding boxes.   
   *In the '\# Channels' box put 9. In the '\# Replicates' box put 1.*

5. Input the columns with the correct intensities.  
  *The columns to import are: Abundance..F1..126..Control,	Abundance..F1..127N..Sample,	Abundance..F1..127C..Sample,	Abundance..F1..128N..Sample,	Abundance..F1..128C..Sample,	Abundance..F1..129N..Sample,	Abundance..F1..129C..Sample,	Abundance..F1..130N..Sample,	Abundance..F1..130C..Sample,	Abundance..F1..131..Sample*

6. Select the column containig the peptide sequences.  
  *Select 'Sequence'*

7. Select the column containing peptide qvality score.  
  *Select 'Qvality.PEP'*
  
8. Select the column contaitng portein accessions.  
*Select Master.Protein.Accessions*

9. Select the radio button **sigmoidal**

10. Input concentrations in the **Enter the vector of Concentrations...**, these should be from smallest to largest, not in log scale and each concentration must be separted by a comma.  
*Input: 1,2,3,4,5,6,7,8*


11. Select one of the plot tabs and wait for the loading sign in the top left corner of the app to finish. 


####Uploading protein fold changes
*(Using the file: sigmoidalFC.csv)* 

1. Select **intensities**. 

2. Select file type.   
  *Select 'csv' options from the radio buttons.*

3. Click **Browse** and select the file.  
  *Select .. from your computer* 

4. Select the correct number of channels and replicates in the corresponding boxes.   
   *In the '\# Channels' box put 9. In the '\# Replicates' box put 1.*

5. Input the columns with the correct log fold changes.  
  *The columns to import are: X126.127_N_norm_log2,	X126.127_C_norm_log2,	X126.128_N_norm_log2,	X126.128_C_norm_log2,	X126.129_N_norm_log2,	X126.129_C_norm_log2,	X126.130_N_norm_log2,	X126.130_C_norm_log2,	X126.131_norm_log2*    
 + For data that are not from PD 2.1, tick the box **Data NOT PD 2.1** insert the column corresponding to the number of Unique Peptides and the Uniprot protein accession numbers from their respective drop down list.
 *This does not apply to the test file supplied in the github*


9. Select the radio button 'sigmoidal'

10. Input concentrations in the **Enter the vector of Concentrations...**, these should be from smallest to largest, not in log scale and each concentration must be separted by a comma.  
*Input: 1,2,3,4,5,6,7,8,9*

11. Select one of the plot tabs and wait for the loading sign in the top left to finish. 

### Gene ID and CRAPome
In the downloaded results DOSCHEDA reports an extra column which contains the number of times (in \%) that a given protein was found as contaminant in a set of experiments. These experiments are organized in what is named *The CRAPome database*, downloaded from http://141.214.172.226/?q=Download and embedded in DOSCHEDA.   
To generate this extra column in the downloaded results, the user should change the organism which will be used to determine the accession number to Gene ID conversion by changing the organism in the **Select your organism:** section in the **Data Upload** tab. 
Currently, the available organisms are Human, Mouse and Yeast, if your organism is not among these, DOSCHEDA will simply return the Human percentages for the matched gene symbols.   
Note that this part of the pipeline will not impact the outcome of the statistical analysis or quality controls, if the organism of interest is not available.    


### Plots
Several plots are available for the visualisation of the results including typical quality control box plots and ranked density distributions.
 


|Plot                          |Description                                                                                                                                                          |Type     |
|:-----------------------------|:--------------------------------------------------------------------------------------------------------------------------------------------------------------------|:--------|
|Box                           |A box plot showing the mean and the interquartile range of each channel                                                                                              |QC       |
|Density and ranked protein    |These plots show the density distribution of each channel and the distribution of the ranked proteins                                                                |QC       |
|Venn                          |The intersection of the kinome and the inputted proteins. There is also the option to load a list of protein names and see the intersection with a personalised list |QC       |
|MeanSD                        |Shows the ranked means with a running median calculated with a window of 10%                                                                                        |QC       |
|Corrgram                      |Pearson Correlation Coefficient between each channel                                                                                                                 |QC       |
|Compare Replicates            |The fold change per protein plotted againt each other in each replicate                                                                                              |Analysis |
|PCA                           |Each channel is plotted in the first two principal components of the data                                                                                            |Analysis |
|Heatmap                       |Interactive heatmap of the values per protein per channel                                                                                                            |Analysis |
|Sigmoidal Model: Top - Bottom |The largest differences between the proteins from the lowest and highest concentrations                                                                               |Analysis |
|Sigmoidal Model: RB50         |The top proteins with significant RB50 values                                                                                                                        |Analysis |
|Sigmoidal Model: Slope      |The top proteins with significant Slope Value                                                                                                                                                                   |Analysis |

Table: Table 3 Available plots with sigmoidal fit. 


### Downloading Results 
From the **Download** tab users can save their processed data by clicking on the **Download Data** button. Also in the same tab, the **Download Report** button enables users to download an HTML report containing all the plots seen in the analysis with descriptions as well as other important information such as the options selected during the workflow including the number of channels, replicates and the statistical fit applied for the data analysis.



### More Informaion and Help 


If you would like to know more about the pipeline used in the DOSCHEDA analysis, please refer to the user manual, this can be accessed at the following https://github.com/brunocontrino/DOSCHEDA .



